apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentmanager.fullname" . }}
  labels:
    {{- include "agentmanager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "agentmanager.selectorLabels" . | nindent 4 }}
