replicaCount: 1

image:
  repository: chrptvn/random-video-be
  tag: 1.0.0-SNAPSHOT
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
    MARIA_DB_HOST: equipment-adapter.production.svc.cluster.local:8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
