replicaCount: 1

image:
  repository: chrptvn/gymbro-be
  tag: 1.0.0-SNAPSHOT
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
