replicaCount: 1

image:
  repository: chrptvn/message-manager
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
  MONGO_USER: root
  MONGO_HOST: mongodb.armada.svc.cluster.local
  MONGO_PORT: 27017
  KAFKA_BOOTSTRAP_SERVERS: kafka-controller-0.kafka-controller-headless.armada.svc.cluster.local:9092

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
