replicaCount: 1

image:
  repository: chrptvn/stablediffusion
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
