replicaCount: 1

image:
  repository: chrptvn/image-servlet
  tag: 1.0.0-SNAPSHOT
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
  IMAGE_PATH: /usr/share/images

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
