
replicaCount: 1

image:
  repository: ghcr.io/invoke-ai/invokeai
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 9090

resources: {}

persistence:
  size: 10Gi
  mountPath: ~/invokeai