
replicaCount: 1

image:
  repository: ghcr.io/invoke-ai/invokeai
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 9090

resources: {}

env:
  CUDA_VISIBLE_DEVICES: 0
  
persistence:
  size: 10Gi
  mountPath: ~/invokeai
