apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-hq.fullname" . }}
  labels:
    {{- include "agent-hq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "agent-hq.selectorLabels" . | nindent 4 }}
