apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invokeai-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ ".Values.persistence.size" | quote }}" }}
  volumeName: invokeai-pv
