apiVersion: v1
kind: PersistentVolume
metadata:
  name: invokeai-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.mountPath }}
  storageClassName: ""